project_id = "fewysenbjhxhqwocttvv"

[functions.send-task-reminders]
verify_jwt = false

[functions.send-habit-reminders]
verify_jwt = false

[functions.send-family-event-reminders]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.microsoft-calendar-sync]
verify_jwt = false
